name = "botsync-relay"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "98f7f5df215cccc750e75aac4bcf76fe"

routes = [
  { pattern = "relay.botsync.io/*", zone_name = "botsync.io" }
]

[[kv_namespaces]]
binding = "PAIRS"
id = "d0494e1890f6469787d7a1128b2910df"

[[kv_namespaces]]
binding = "NETWORKS"
id = "5a702c8d705a402590d3a83c230a798b"

[vars]
CORS_ORIGIN = "https://botsync.io"
